apiVersion: batch/v1
kind: Job
metadata:
  name: chrwp-job
spec:
  template:
    spec:
      containers:
      - name: chrwp-job
        image: yash5090/chrwp:latest
        ports:
        - containerPort: 5000
      restartPolicy: OnFailure
