apiVersion: apps/v1
kind: Deployment
metadata:
  name: chrwp-deployment
spec:
  replicas: 6 # You can adjust the number of replicas as needed
  selector:
    matchLabels:
      app: chrwp
  template:
    metadata:
      labels:
        app: chrwp
    spec:
      containers:
        - name: chrwp
          image: yash5090/chrwp:latest # Replace with the actual image tag
          ports:
            - containerPort: 5000 # Replace with the port your Tetris game listens on
